jobs:
  include:
   - os: linux
     arch: amd64
     dist: bionic
     virt: lxd
     group: edge
   - os: linux
     arch: amd64
     dist: focal
     virt: lxd
     group: edge    
language: C
install:
  - sudo add-apt-repository ppa:tkchia/build-ia16 -y
  - sudo apt-get update
  - echo "${TRAVIS_BUILD_DIR}"
  - sudo apt install gcc-ia16-elf nasm upx wget -y
script:
  - bash ci_build.sh
  - bash ci_test.sh
